#!/bin/bash
# Serve mgreport
# Should not be called directly

if [[ -z $MGREPORT ]]; then
    echo "This script needs to call within \"mgreport\""
    exit -2
fi

# script starts here
regrex_full='^([0-9]{4})\.([0-9]{2})_([0-9])$'
regrex_half='^([0-9]{4})\.([0-9]{2})$'
regrex_year='^([0-9]{4})$'

if [[ $# -lt 1 ]]; then
    echo "List all reports"
    cd $REPORT_HOME
    ls -d *.*_*
    exit 0
fi

if [[ $1 =~ $regrex_full ]]; then
    year=${BASH_REMATCH[1]}
    month=${BASH_REMATCH[2]}
    number=${BASH_REMATCH[3]}
    echo "List reports for $year.${month}_$number"
    echo
    ls $REPORT_HOME/$year.${month}_$number
elif [[ $1 =~ $regrex_half ]]; then
    year=${BASH_REMATCH[1]}
    month=${BASH_REMATCH[2]}
    echo "List reports for YEAR.MONTH $year.${month}"
    echo
    ls $REPORT_HOME/$year.${month}_*
elif [[ $1 =~ $regrex_year ]]; then
    year=${BASH_REMATCH[1]}
    echo "List report for YEAR $year"
    echo
    ls $REPORT_HOME/$year.*
else
    echo "Error: wrong options for -l"
    print_usage
    exit 1
fi