#!/bin/bash
# Serve mgreport
# Should not be called directly

if [[ -z $MGREPORT ]]; then
    echo "This script needs to call within \"mgreport\""
    exit -2
fi

# script starts here
regrex='^([0-9]{4})\.([0-9]{2})_([0-9])'

report_to_work_on=""

if [[ $# -lt 1 ]]; then
    cd $REPORT_HOME
    reports=($(ls -d *.*_*))
    report_to_work_on=${reports[-1]}
    echo "Working on most recent report: $report_to_work_on"
else
    if [[ $1 =~ $regrex ]]; then
        year=${BASH_REMATCH[1]}
        month=${BASH_REMATCH[2]}
        number=${BASH_REMATCH[3]}
        report_to_work_on=$year.${month}_$number
    else
        echo "Error: wrong report name format"
        print_usage
        exit -1
    fi
fi

if ! [[ -e $REPORT_HOME/$report_to_work_on ]]; then
    echo "Report '$report_to_work_on' doesn't exist"
    exit -3
fi

echo "Opening $report_to_work_on in file explorer"
cd $REPORT_HOME/$report_to_work_on
if ! [[ -z $FILEEXPLORER ]]; then
    $FILEEXPLORER .
else
    echo "\$FILEEXPLORER not defined, skip opening directory in file explorer"
fi

if [[ -z $EDITOR ]]; then
    echo "Error: \$EDITOR not defined"
else
    echo "Opening $report_to_work_on in $EDITOR"
    $EDITOR .
fi